version: '3.8'

services:

  db:
    build: ./database
    networks:
      - backend-net
    volumes:
      - ./database/data:/var/lib/postgresql/data

  auth:
    build: ./auth-service
    depends_on:
      - db
    networks:
      - backend-net

  api-gateway:
    image: nginx:1-alpine
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - auth
    networks:
      - backend-net
      - frontend-net

  frontend:
    build: ./front-end
    depends_on:
      - api-gateway
    networks:
      - frontend-net

networks:
  backend-net:
  frontend-net: