version: '3.8'

services:

  db:
    build: ./database
    container_name: db
    networks:
      - backend-net
    volumes:
      - ./database/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"  # Expose for debugging

  auth:
    build: ./auth-service
    container_name: auth
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-net
    ports:
      - "8082:8080"  # Changed from 8080:8080 to avoid port conflict
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=root
      - DB_PASSWORD=root

  api-gateway:
    image: nginx:1-alpine
    container_name: api-gateway
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - auth
    networks:
      - backend-net
      - frontend-net
    restart: on-failure

  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "8081:80"
    depends_on:
      - api-gateway
    networks:
      - frontend-net

  blockchain:
    build: ./blockChaine-microservice
    container_name: blockchain
    ports:
      - "5000:5000"
    networks:
      - backend-net
    volumes:
      - ./blockChaine-microservice:/app
    restart: on-failure

  document-service:
    build: ./document-service
    container_name: document-service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"
    networks:
      - backend-net
    volumes:
      - ./document-service/uploads:/app/uploads
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=root
      - DB_PASSWORD=root
      - BLOCKCHAIN_SERVICE_URL=http://blockchain:5000
    restart: on-failure

  crypto-service:
    build: ./digital-signature-app-main
    container_name: crypto-service
    ports:
      - "8000:8000"
    networks:
      - backend-net
    volumes:
      - ./digital-signature-app-main/keys:/app/keys
      - ./digital-signature-app-main/input:/app/input
      - ./digital-signature-app-main/output:/app/output
    restart: on-failure

networks:
  backend-net:
    name: backend-net
  frontend-net:
    name: frontend-net
